version: '3'
services:
  web:
    build: .
    image: andrewmc/mortimer_web:0.0.2
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data:/mnt/data
      - ./awsdeploy/odoo:/etc/odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo